---
title: "Data inport"
author: "Yingxi Ji"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Load the dataset
```{r}
## read in a dataset
litters_data = read_csv(file = "./data/FAS_litters.csv")

# names(litters_data)
 litters_data = janitor::clean_names(litters_data)
# names(litters_data)

## change the data type


## litters_data = read_csv(file = "./data/FAS_litters.csv",
#  col_types = cols(
#   `Litter Number` = col_character(),
#    `GD0 weight` = col_double(),
#   `GD18 weight` = col_double(),
#  `GD of Birth` = col_integer(),
# `Pups born alive` = col_integer(),
#`Pups dead @ birth` = col_integer(),
# `Pups survive` = col_integer()
#  )
#)


# litters_data = read_csv(file = "./data/FAS_litters.csv",
 # col_types = "ccddiiii"
#)
#litters_data

pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
#skimr::skim(litters_data)
```

## Slecting 
```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
select(litters_data, litter_number, gd0_weight, pups_born_alive, starts_with("pups"))
select(litters_data, litter_number, gd0_weight:pups_born_alive)
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)

```

## Filtering
```{r}
filter(litters_data, group == "Con7")
filter(litters_data,gd_of_birth == 20)
filter(litters_data,gd_of_birth >= 20)
filter(litters_data,pups_born_alive < 6, group =="Con7")

filter(litters_data, group %in% c("Con7", "Con8"))
# filter(litters_data, group=="Con7" | group =="Con8")

filter(litters_data, gd0_weight+gd18_weight <80)

# Do not do this 
# filter(litters_data, is.na(gd0_weight))
drop_na(litters_data, gd0_weight)
```

# Mutate 
```{r}
mutate(litters_data,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```

## Arrange 
```{r}
arrange(litters_data, pups_born_alive)

#Descending
arrange(litters_data, desc(pups_born_alive)) 


```


